config/routes.rb
Rails.application.routes.draw do
  get 'articles/index'
  get 'articles/new'
  get 'articles/edit'
  get 'articles/delete'
  get 'articles/show'
  get 'articles/sms'
  get 'welcome/index'
  
  resources :articles do
    resources :comments
  end

  mount KannelRails::Engine => '/sms'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy

  validates :title, presence:true,
                    length: { minimum: 5 }

  validates :text, presence:true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  layout false

  http_basic_authenticate_with name: "josiah", password: 'asdf', except: [:index, :show]
  
  def index
    @articles = Article.all
    # render plain: @articles.inspect
  end

  def new
    @article = Article.new
  end
  
  def create 
    # render plain: params[:article].inspect
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end
  
  def update 
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  def show
    @article = Article.find(params[:id])
  end
  
  def sms
    KannelRails.send_message("+639001234567", "Hello")
  end

  private 

    def article_params
      params.require(:article).permit(:title, :text)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "josiah", password: "asdf", only: :destroy
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
  
  def destroy
    @article = Article.find(params[:article_id])
    Comment.find(params[:id]).destroy
    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
  <%= form.label :title %><br />
  <%= form.text_field :title %>
  </p>

  <p>
  <%= form.label :text %><br />
  <%= form.text_area :text %>
  </p>

  <p>
  <%= form.submit %>
  </p>
<% end %>

app/views/articles/delete.html.erb
<h1>Articles#delete</h1>
<p>Find me in app/views/articles/delete.html.erb</p>

app/views/articles/edit.html.erb
<h1>New Article </h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h2>Articles</h2>
<%= link_to 'New Article', new_article_path %>
<table>

  <tr>
    <th>Title</th>
    <th>Text</th>
    <th>Read</th>
  </tr>
  <% @articles.each do |article| %>
    <tr>
        <td><%= article.title %></td>
        <td><%= article.text %></td>
        <td>
          <%= link_to 'Show Article', article_path(article) %>
          <%= link_to 'Edit Article', edit_article_path(article) %>
          <%= link_to 'Delete Article', article_path(article),
              method: :delete,
              data: {confirm: 'Are you sure?' } %>
        </td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New Article </h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
<strong>Title:</strong>
<%= @article.title %>
</p>
<p>
<strong>Text:</strong>
<%= @article.text %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/articles/sms.html.erb
test

app/views/comments/_comment.html.erb
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>

  <p>
    <%= link_to 'Delete Comment', [comment.article, comment],
                method: :delete,
                data: { confirm: 'Are you wure?' } %>
  </p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br />
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>

<%= link_to 'My Blog', controller: 'articles' %>